### ISSUE TITLE
Add a check for empty data

### ISSUE THREAD

**Issue by Snafuuz** [kainjow/Mustache#16]
I have some cases in which it would be nice to know if a certain data object contains any attribute or not. This could easily be done by adding a new function to the data class:

bool is_empty_object() const {
    return is_object() && obj_->empty();
}

**Comment by kainjow** [comment]
Feel free to submit a pull request!

**Comment by Snafuuz** [comment]
I tried, but it seems I don‘t have permission to create another branch and push my changes there. 
I‘m reluctant to create a fork if the whole repo for such a tiny change

I can push the change and create a pull request if you can grant me push permission

**Comment by kainjow** [comment]
Check out https://help.github.com/articles/creating-a-pull-request-from-a-fork/
