### ISSUE TITLE
Newlines are not HTML escaped

### ISSUE THREAD

**Issue by Snafuuz** [kainjow/Mustache#18]
The mustache documentation says:
"All variables are HTML escaped by default."

The documentation is not very explicit about newlines in this context, but I think they should be converted to <br> tags, so a value can also have multiple lines and still be rendered correctly, including line breaks.

The problem can of course be avoided by using a custom escaping function, but I assume the correct behaviour would be to translate newlines into <br> by default

**Comment by Snafuuz** [comment]
=> I filed a pull request with a change that adds newline conversion to the HTML escape function

**Comment by kainjow** [comment]
See my comments in the PR.
