### ISSUE TITLE
Partials don't respect overridden delimiters

### ISSUE THREAD

**Issue by KitsuneRal** [kainjow/Mustache#20]
Case in point: using the following template:
```mustache
{{=[+ +]=}}[+>partial+]
```
and assuming I have `partial` defined as
```
{{^nothing}}1{{/nothing}}[+^nothing+]2[+/nothing+]
```
I see
```
1[+^nothing+]2[+/nothing+]
```
rather than
```
{{^nothing}}1{{/nothing}}2
```
I wonder if it's a bug or a feature. The original Mustache manual is silent on this case.

**Comment by kainjow** [comment]
Looks like this covers it: https://github.com/mustache/spec/blob/master/specs/delimiters.yml#L73
