### ISSUE TITLE
Unmatching sections are hard to pinpoint

### ISSUE THREAD

**Issue by KitsuneRal** [kainjow/Mustache#28]
Mustache before 4.0b2 (both 3.x and 4.0b1) is not really helpful when it comes to mistakes in section names. As much as I remember, rather than indicate the nearest non-matching section, Mustache was usually stopping at some outer section very far from the actual error, or even at the end of file, which makes debugging convoluted templates quite a chore.

**Comment by kainjow** [comment]
I think this is generally an issue with naive parsers. Mustache just uses a home-grown parser so it's kind of dumb. I imagine using a text editor that knows about Mustache kind of like how some do with HTML (syntax highlighting, code folding, etc) would be beneficial when working on more complex sources.

I'm going to close for now as I have no plans for this.
