### ISSUE TITLE
Missing #include <cctype>

### ISSUE THREAD

**Issue by Quincunx271** [kainjow/Mustache#29]
Mustache uses `std::isspace`, which lives in the `cctype` header (well, it uses `isspace` but should probably use `std::isspace`). This `#include` is missing, which means that Mustache fails to build on Visual Studio 2017.

**Comment by kainjow** [comment]
It's setup with AppVeyor for testing with 2013, 2015 and 2017. I wonder if this is a recent change in 2017. Could you make a pull request?

**Comment by Quincunx271** [comment]
It may be a recent VS 2017 change, or maybe it's because of the `/permissive-` flag I'm passing to MSVC.

I'll go ahead and make a PR

**Comment by kainjow** [comment]
Ah yeah, that's probably it.
