### ISSUE TITLE
Intent to package for Debian

### ISSUE THREAD

**Issue by legoktm** [kainjow/Mustache#36]
Hi,

I just wanted to let you know that I'm planning to package this for Debian: <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931738>.

Did you have any estimated time of when 4.0 would be ready?

**Comment by kainjow** [comment]
No plans right now, although I'd like to finish up the remaining bugs.

**Comment by kainjow** [comment]
I just released version 4.0.
