### ISSUE TITLE
Rename library + move into subfolder?

### ISSUE THREAD

**Issue by a-teammate** [kainjow/Mustache#4]
Hey,
Im currently creating a package on conan.io for your project.

But I'm wondering how am I supposed to name it?

Simply "Mustache" wouldn't distinct it from other mustache implementations in C++.  
And since we speak about name clashes already: what about moving the headers into its own folder, so its `#include <kainjow/mustache.hpp>` or am I allowed to just do that for the package?

PS: We are already using your lib (inexor-game) for a build tool and are happy with it.

**Comment by kainjow** [comment]
I'm not familiar with Conan. It doesn't have vendor namespacing? That would solve the problem. For example import "kainjow/mustache".

Can't you just point your include directory to the Mustache repository? Then you can `#include <Mustache/mustache.hpp>`.

How is this package being created? Is it not based off the git repository?

**Comment by a-teammate** [comment]
Sure thats doable.
But I wanted to make sure you are okay with this since you didn't do it in the github repo.

So I'll just install the headers into "kainjow/" and let the users include "kainjow/mustache.hpp", thanks :)

The package is created by providing a conanfile.py in another repository, which does check out your git repo.

**Comment by kainjow** [comment]
That should be fine.
