### ISSUE TITLE
use of flath_hash maps

### ISSUE THREAD

**Issue by patlecat** [kainjow/Mustache#49]
Hi again

I see you use the standard STL maps. I was looking into faster alternatives and among others I found the Abseil **flat_hash_map** container from Google. The use of this should speed up your code by factors I can imagine. What do you think about it?
https://abseil.io/docs/cpp/guides/container

**Comment by kainjow** [comment]
Hi, thanks for the suggestion but I'd prefer to use STL so there are no third-party dependencies.

I am open to making the container types customized through templates though.

**Comment by patlecat** [comment]
Yeah, a plugin mechanism to use alternate containers would be fine too.
