### ISSUE TITLE
Make HTML escapes optional

### ISSUE THREAD

**Issue by a-teammate** [kainjow/Mustache#5]
Currently if we drop in templatedata like `vector<int>`  it will render as `vector&lt;int&gt;`

A switch for the renderComponent() function would be cool.

I think even a macro would be sufficient if you do not want to add a "bool escape = true" to the arguments list of "render()"
but probably a complete "Options" enum would be better

**Comment by kainjow** [comment]
You can use triple mustache syntax for this:

> All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

See the documentation [here](https://mustache.github.io/mustache.5.html#TAG-TYPES).

**Comment by a-teammate** [comment]
ah thank you :)
