### ISSUE TITLE
Request method to initialize with alternate delimiters

### ISSUE THREAD

**Issue by derekbsnider** [kainjow/Mustache#56]
I think it would be particularly useful if there was a way to set what the tag delimiters were on the mustache object directly.

Example:

```
mustache tmpl{"Hello <%%what%%>!"};

tmpl.set_delimiters("<%% %%>");
std::cout << tmpl.render({"what", "World"}) << std::endl;

```

**Comment by KitsuneRal** [comment]
Well, Mustache is not just double curly braces, the list of conventions is much longer... Even after redefining the delimiter the template language remains Mustache. But I remembered that there's already `set_custom_escape()` anyway that also changes language metadata, and delimiter assignment falls in that category as well.

**Comment by derekbsnider** [comment]
How would one change the delimiter using `set_custom_escape() `?

**Comment by KitsuneRal** [comment]
One cannot; `set_custom_escape()` is for a different thing.

**Comment by derekbsnider** [comment]
Also have a case where being able to set the default delimiter outside of the template would be more important -- if you need to apply the template line by line, and do not have access to the whole document (i.e. inside of a stream filter).

**Comment by kainjow** [comment]
Seems low use currently. Feel free to submit a PR with a test, and I'll consider it.
