### ISSUE TITLE
Parser chokes on open tags without close

### ISSUE THREAD

**Issue by derekbsnider** [kainjow/Mustache#57]
If the template contains dangling open tags, there will be no output (note, this works with https://github.com/no1msd/mstch).

Example:

```
int main()
{
    mustache tmpl{"Hello {{what}}! {{"};

    std::cout << "Rendered: " << tmpl.render({"what", "there"}) << std::endl;

    return 0;
}
```

**Output:**
Rendered:

**Expected:**
Rendered: Hello there! {{

**Comment by kainjow** [comment]
Did you check `is_valid()` and `error_message()`?

**Comment by derekbsnider** [comment]
I was expecting this implementation to work the same as the original.

**Comment by kainjow** [comment]
There are multiple implementations. I don’t think any can be classified as “original.”
