### ISSUE TITLE
basic_data could be a std::variant

### ISSUE THREAD

**Issue by the-moisrex** [kainjow/Mustache#64]
Is there a reason (other than the project being designed for older C++ versions) that `basic_data` isn't `std::variant` or at least implemented a bit like `std::variant`? Why so many unique_ptrs laying around?

```c++
private:
    type type_;
    std::unique_ptr<basic_object<string_type>> obj_;
    std::unique_ptr<string_type> str_;
    std::unique_ptr<basic_list<string_type>> list_;
    std::unique_ptr<basic_partial<string_type>> partial_;
    std::unique_ptr<basic_lambda_t<string_type>> lambda_;

```

**Comment by kainjow** [comment]
Yes the project was written for C++11.

**Comment by ivanstepanovftw** [comment]
We are in 2023

**Comment by the-moisrex** [comment]
I've changed the source code of this project is so many ways that I hardly recognize the old code and I'm still not satisfied with how it's storing the AST.

[Here](https://github.com/the-moisrex/webpp/blob/595fec346e2bb25c3b105f852150e6eb52478bec/webpp/views/mustache_view.hpp)'s my implementation which works in C++20.

I still have work to do thought but I have my hands full the framework.

[issue](https://github.com/the-moisrex/webpp/issues/242), [issue](https://github.com/the-moisrex/webpp/issues/120), and the [most annoying issue](https://github.com/the-moisrex/webpp/issues/187).

**Comment by kainjow** [comment]
I'm happy to review a PR for this change that keeps existing functionality behind some type of if-def. Thanks.
