### ISSUE TITLE
Expanding template string in lambda to value

### ISSUE THREAD

**Issue by sebsjoberg** [kainjow/Mustache#7]
When invoking a lambda, as far as I can tell, it's not possible to expand the actual value within the lambda. Instead you get the tag in the string of the lambda.

Would it be possible to have another type of lambda where you could call render on the string with the correct context?

Below is an example of a lambda that would benefit from some way to render the value within.

```
struct right_pad {
  right_pad(int n) : nbr(n) {}
  int nbr;
  std::string operator()(const std::string text) {
    std::string padded(text);
    padded.resize(nbr, ' ');
    return padded;
  }
};

**Comment by kainjow** [comment]
I've added this. There's a new `lambda2` type that takes a second argument `const renderer& render` and you can call this to render any text. Please take a look when you get a chance!
