### ISSUE TITLE
Consider allowing defining a custom Context for providing values on-demand

### ISSUE THREAD

**Issue by vadz** [kainjow/Mustache#9]
In my case it would be far more convenient to use an existing function for looking up the values of variables embedded in Mustache templates, but this doesn't currently possible and all variables and partials need to be defined beforehand. This is especially annoying for the latter, as partials are basically just files, so they need to be read from disk and provided as part of the data, even if they end up not being used at all by the current template.

So I'd basically like to be able to provide my own `Context` and override its `get()` method. I realize that it's not completely trivial because it would need to be refactored to separate `push/pop()` and `get()` methods, but it would be nice to be able to do this.

**Comment by kainjow** [comment]
Partials are implemented as lambdas so they're only used when needed.

I'm curious about why you need this? Are you mapping to some dynamic data set?

**Comment by kainjow** [comment]
What about assigning a callback that can be used when a variable is not found? Then it can return a data object based on the variable name. For example:

```
using not_found_handler = std::function<data(const string& variable);
```

Do you need to handle dot syntax though (e.g. var.prop)?

**Comment by vadz** [comment]
> Partials are implemented as lambdas so they're only used when needed.

Used, yes, but they still need to be registered in advance.

> I'm curious about why you need this? Are you mapping to some dynamic data set?

Yes, something like that. In particular, I have many vectors that are not always used and I'd like to access them via `{{vec[n]}}` kind of expressions without having to register them for all values of n.

**Comment by vadz** [comment]
> What about assigning a callback that can be used when a variable is not found?

This would be indeed sufficient for my needs, I'd just use this for everything instead of using the normal variable definition. However the call back should also get the kind of expression being looked up, i.e. "partial", "section" or "variable".

It still seems like allowing to replace the existing handler with a custom one would be slightly more flexible and, perhaps, more elegant too. But, again, in my particular case such handler would be enough.

**Comment by kainjow** [comment]
Yes, I agree. I'll look into it.

**Comment by kainjow** [comment]
I added a basic implementation in 1bfc1fc for this. Take a look and let me know what you think.

**Comment by KitsuneRal** [comment]
Actually, I'm sitting here with the same need - I want to read a partial from a file and have no way of knowing in advance which file would that be. The basic implementation seems to fall short just one small step (or I don't understand how to use contexts) - I would like to use `mustache::context` for a base class, in order to reuse its `get()` and `push/pop()` and only overriding `get_partial()` (because I have ordinary `data` and partials in files at the same time). Does it make sense to open up `mustache::context` as well or am I just missing an elephant in the room?

**Comment by vadz** [comment]
@kainjow Thanks, this looks good to me. I didn't have time to try using this in my real code, but I'll do it and let you know if I run into any problems.

The only comment I have about the changes is that it's a bit weird to have a data file `delimiterSet` in a base class with only pure virtual functions. Why is it needed there?

**Comment by kainjow** [comment]
@KitsuneRal can you give an example of an example data set you're working with? Are you providing a service for other data you're not in control of? Trying to understand why you don't know in advance the data.

@vadz agreed it's kind of awkward that delimiterSet is there. I'll find a way to move it out.

**Comment by kainjow** [comment]
@vadz I added an internal wrapper class in c1978db so `delimiterSet` is no longer part of the public class.

**Comment by KitsuneRal** [comment]
@kainjow sure. I'm making a code generator (https://github.com/KitsuneRal/api-generator) that could use arbitrary templates for input, as soon as they follow the context I define in the generator. The relevant (and so far very early) code using Mustache is here: https://github.com/KitsuneRal/api-generator/blob/master/printer.cpp
And here's an example Mustache file: https://github.com/QMatrixClient/libqmatrixclient/blob/kitsune-apigen/jobs/%7B%7Bbase%7D%7D.h.mustache - you can see a `{{#@filePartial}}` construct above, which is actually a workaround to load a partial from another file on-demand (see the `Printer` source code).

**Comment by kainjow** [comment]
I can make the context class public then you could override get_partial and implement custom file reading. Suppose I could provide this as optional built-in with std file lib for convenience too.

**Comment by KitsuneRal** [comment]
Thanks! But I'm actually not entirely sure that reading files is worth being inside the library. E.g., when I made that convenience construct myself, I realised that a question about search paths in general case is open-ended, so a configuration point should be there. And then there're security issues, like whether you should allow travelling up the file structure (`{{>../../etc/passwd}}`) - sometimes yes, sometimes no. For that reason, I'd say that an extension point for `get_partial()` and the like would be just right.

**Comment by kainjow** [comment]
@KitsuneRal I made `context` public so it can be overridden and added an example test in 1289f78.

**Comment by KitsuneRal** [comment]
@kainjow Thank you! Looks fine, will try to actually use it in the nearest days.
